In [1]:
import pandas as pd

## working with JSON

In [3]:
pd.read_json("demand.json")

,Date,Daily Metered,Non Daily Metered (NDM),Large Daily Metered (LDM) non Power Gen,Power Generation,Total ROI demand
0,2021-01-01,7.816340,61.593662,9.972410,98.520732,177.903144
1,2021-01-02,8.819988,64.817927,11.365715,97.945353,182.948983
2,2021-01-03,8.363208,65.084971,11.926284,99.608449,184.982912
3,2021-01-04,11.070071,73.712590,13.402225,110.697948,208.882834
4,2021-01-05,11.696971,72.342131,14.098853,117.179088,215.317043
...,...,...,...,...,...,...
815,2023-03-27,11.724638,42.022084,16.653183,96.804983,167.204888
816,2023-03-28,11.615986,36.067673,17.409996,86.123295,151.216950
817,2023-03-29,10.494077,31.234414,16.734978,65.188326,123.651795
818,2023-03-30,11.055787,28.099440,17.299754,89.901483,146.356464
819,2023-03-31,10.600473,33.663102,17.014904,86.796231,148.074710

In [4]:
pd.read_json("https://storage.googleapis.com/kagglesdsdata/datasets/3508933/6130007/2023q1dailydemandjson.json?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20251016%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20251016T133701Z&X-Goog-Expires=259200&X-Goog-SignedHeaders=host&X-Goog-Signature=8aeea85e8a54f173479d8c59fa1a0fcda2c7b3a2025c271075d5848047ec0a65a8c941b04776284cf7efa60ecd69d87cd7f4364e26bb60ef8da3103533d519b5418aa5c185f97c9ed4d20e679fb94fb2ff4d95f17f4b8569723db22face99367d0229a667d57609972fd2a7839e9e96d5588a3ca7de843ed98e255078b1b7f476698e5c400c41be8c4b72a9e8cab96a4d267184862ecb0a21b5a30af01306f06fedecf2921f476caf2879748f860dff1c296d3f59b53cd8ea0fcd90898ad8de792772e1eaf2aa25fc71cfef2c43135dedaebf2c8f982ef0dfbccd2a272eca18e5394236ae01bc0056ae1a12a92471ce1dc230ec2d0493e414ab114d9a252013b")

,Date,Daily Metered,Non Daily Metered (NDM),Large Daily Metered (LDM) non Power Gen,Power Generation,Total ROI demand
0,2021-01-01,7.816340,61.593662,9.972410,98.520732,177.903144
1,2021-01-02,8.819988,64.817927,11.365715,97.945353,182.948983
2,2021-01-03,8.363208,65.084971,11.926284,99.608449,184.982912
3,2021-01-04,11.070071,73.712590,13.402225,110.697948,208.882834
4,2021-01-05,11.696971,72.342131,14.098853,117.179088,215.317043
...,...,...,...,...,...,...
815,2023-03-27,11.724638,42.022084,16.653183,96.804983,167.204888
816,2023-03-28,11.615986,36.067673,17.409996,86.123295,151.216950
817,2023-03-29,10.494077,31.234414,16.734978,65.188326,123.651795
818,2023-03-30,11.055787,28.099440,17.299754,89.901483,146.356464
819,2023-03-31,10.600473,33.663102,17.014904,86.796231,148.074710

## working with sql dataset

In [12]:
import mysql.connector

In [ ]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",        
    password="",
    database="world"   
)

print("✅ Connected successfully!")

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: NO)