fill or drop data on missing value

In [1]:
import pandas as pd
data = pd.read_csv("data.csv")
data

      name  score       city  placement
0    Aarav   85.6      Delhi        1.0
1     Isha    NaN     Mumbai        0.0
2    Rohan   91.2        NaN        1.0
3    Meera   67.8       Pune        NaN
4    Kabir   88.5  Hyderabad        1.0
5   Simran    NaN    Chennai        1.0
6    Arjun   59.3    Kolkata        0.0
7      NaN   82.1      Delhi        1.0
8      Dev   94.7  Bangalore        1.0
9   Ritika   63.5        NaN        0.0
10   Kunal   78.4       Pune        1.0
11    Neha   81.9  Hyderabad        NaN
12     Raj   55.2    Chennai        0.0
13   Priya    NaN    Kolkata        1.0
14  Aditya   69.4      Delhi        0.0

In [2]:
#proper data handing - name null remove, score - mean, city- mod, placment - 0

# #name null remov
data = data.dropna(subset="name").copy()

# #placment - 0
data["placement"] = data["placement"].fillna(0) 

#city - mode
mfreq = data["city"].mode()[0]
data["city"] = data["city"].fillna(mfreq)

#score - mean
data["score"] = data["score"].fillna(data["score"].mean())

data

      name      score       city  placement
0    Aarav  85.600000      Delhi        1.0
1     Isha  75.954545     Mumbai        0.0
2    Rohan  91.200000    Chennai        1.0
3    Meera  67.800000       Pune        0.0
4    Kabir  88.500000  Hyderabad        1.0
5   Simran  75.954545    Chennai        1.0
6    Arjun  59.300000    Kolkata        0.0
8      Dev  94.700000  Bangalore        1.0
9   Ritika  63.500000    Chennai        0.0
10   Kunal  78.400000       Pune        1.0
11    Neha  81.900000  Hyderabad        0.0
12     Raj  55.200000    Chennai        0.0
13   Priya  75.954545    Kolkata        1.0
14  Aditya  69.400000      Delhi        0.0

In [3]:
#export data as csv
data.to_csv("after01.csv", index=False)